name: CI Firebase Hosting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
        
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.2
      env:
        FIREBASE_TOKEN: 1//0hCSyGH1USUZ9CgYIARAAGBESNwF-L9IrMD27Jwool497Mf3ruUekgdsJq3aY_2BCD62S1nuX7CdPrtAxq-5ONCT5KPh2O2d6JH8
        FIREBASE_PROJECT: name-of-the-project
